# Generated by Django 5.1.2 on 2024-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='contraseña',
        ),
    ]
