# Generated by Django 5.1.2 on 2024-11-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_contrasena_usuario_contraseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
