# Generated by Django 5.1.2 on 2024-11-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_notificacion_registroasignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasignacion',
            name='idIncidencia',
        ),
        migrations.RemoveField(
            model_name='registroasignacion',
            name='idUsuario',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='RegistroAsignacion',
        ),
    ]
