# Generated by Django 5.1.2 on 2024-10-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_logo_nombre_municipalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
