# Generated by Django 5.1.2 on 2024-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
