# Generated by Django 5.1.3 on 2024-11-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_formulario_campo_opcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='campo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
    ]
