# Generated by Django 5.1.3 on 2024-11-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_remove_campo_formulario_remove_opcion_campo_and_more'),
        ('gestor_territorial', '0006_alter_incidencia_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada'), ('no verificada', 'No Verificada')], max_length=15, null=True)),
                ('estado_actual', models.CharField(choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada'), ('no verificada', 'No Verificada')], default='iniciada', max_length=15)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, null=True)),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria', to='gestor_territorial.incidencia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
