# Generated by Django 5.1.3 on 2024-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_alter_campo_tipo_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
