# Generated by Django 5.1.3 on 2024-11-29 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_territorial', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipalidad', models.CharField(default='Municipalidad X', max_length=255, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='logos/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateField()),
                ('estado', models.CharField(max_length=12)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
