# Generated by Django 5.1.2 on 2024-11-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_territorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipalidad', models.CharField(default='Municipalidad X', max_length=255, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='logos/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], max_length=15, null=True)),
                ('estado_actual', models.CharField(choices=[('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], default='iniciada', max_length=15)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, null=True)),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria', to='gestor_territorial.incidencia')),
            ],
        ),
    ]
