# Generated by Django 5.1.3 on 2024-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroauditoria',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registroauditoria',
            name='fechaAsignacion',
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='estado_actual',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], default='iniciada', max_length=15),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
