# Generated by Django 5.1.3 on 2024-11-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_registroauditoria_estado_and_more'),
        ('gestor_territorial', '0005_remove_incidencia_direccion_multimedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='idIncidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria', to='gestor_territorial.incidencia'),
        ),
    ]
