# Generated by Django 5.1.3 on 2024-12-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='estado_actual',
            field=models.CharField(choices=[('eliminada', 'eliminada'), ('inexistente', 'inexistente'), ('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], default='iniciada', max_length=15),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('eliminada', 'eliminada'), ('inexistente', 'inexistente'), ('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], max_length=15, null=True),
        ),
    ]
