# Generated by Django 5.1.2 on 2024-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_logo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMunicipalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Municipalidad X', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
