# Generated by Django 5.1.2 on 2024-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
