# Generated by Django 5.1.3 on 2024-11-11 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_usuario_contrasena'),
        ('gestor_territorial', '0012_remove_incidencia_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado_lectura', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.usuario')),
                ('incidenciaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsignacion',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateField()),
                ('estado', models.CharField(max_length=12)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.usuario')),
            ],
        ),
    ]
