# Generated by Django 3.2.15 on 2024-10-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIndicencia', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fkUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario')),
            ],
        ),
    ]
