# Generated by Django 5.1.2 on 2024-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario_gestorTerritorial', models.IntegerField()),
                ('titulo_Incidencia', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_Hora_Reporte', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('tipo_Incidencia', models.CharField(max_length=100)),
                ('medios_Adjuntos', models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/')),
                ('fecha_estimada_fin', models.DateField(blank=True, null=True)),
                ('comentarios_anexos', models.TextField(blank=True, null=True)),
                ('historial_Cambios_estados', models.JSONField(default=dict)),
                ('resolutor_Asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('informe_Final', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
