# Generated by Django 5.0 on 2024-11-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_multimedia', models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/')),
                ('titulo_Incidencia', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('iniciada', 'Incidad'), ('rechazada', 'Rechazada'), ('aprobada', 'Inciada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada')], default='pendiente', max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_Reporte', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('historial_Cambios_estados', models.JSONField(default=dict)),
                ('usuario_Asignado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('g.t', 'Gestor Territorial'), ('d', 'Director'), ('dep', 'Departamento de obras'), ('r', 'Resolutor')], max_length=1000)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(default='12345', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dobras.incidencia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dobras.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('idincidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dobras.incidencia')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dobras.usuario')),
            ],
        ),
    ]
