# Generated by Django 5.0 on 2024-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dobras', '0003_remove_incidencia_historial_cambios_estados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='contraseña',
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada')], default='pendiente', max_length=15),
        ),
    ]
