# Generated by Django 5.1.2 on 2024-11-17 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dobras', '0005_alter_registroasignacion_estado'),
        ('gestor_territorial', '0012_remove_incidencia_comentarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='idincidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia'),
        ),
        migrations.AlterField(
            model_name='registroasignacion',
            name='idIncidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia'),
        ),
        migrations.AlterField(
            model_name='registroasignacion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
