# Generated by Django 5.1.3 on 2024-11-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dobras', '0006_alter_notificaciones_idincidencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
