# Generated by Django 5.1.2 on 2024-11-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_Formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(default='Inactivo', max_length=10)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('descripcion', models.TextField()),
                ('fkUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario')),
            ],
        ),
    ]
