# Generated by Django 4.1 on 2024-11-02 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incidencia",
            old_name="nombreIndicencia",
            new_name="nombre",
        ),
    ]
