# Generated by Django 5.1.2 on 2024-11-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_Formulario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
