# Generated by Django 5.1.2 on 2024-11-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_territorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada')], default='pendiente', max_length=15)),
                ('comentario', models.TextField()),
                ('idIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_territorial.incidencia')),
            ],
        ),
    ]
