# Generated by Django 5.1.3 on 2024-12-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dobras', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAsignacion',
        ),
    ]
