# Generated by Django 5.0 on 2024-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dobras', '0004_rename_contrasena_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasignacion',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada')], default='pendiente', max_length=15),
        ),
    ]
