# Generated by Django 5.1.2 on 2024-11-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
