# Generated by Django 5.1.2 on 2024-11-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
