# Generated by Django 5.1.3 on 2024-11-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='tipo_Incidencia',
        ),
    ]
