# Generated by Django 5.1.3 on 2024-11-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0003_rename_comentarios_incidencia_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='comentario',
            new_name='comentarios',
        ),
    ]
