# Generated by Django 5.1.3 on 2024-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0004_rename_comentario_incidencia_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='comentariosF',
            field=models.TextField(blank=True, null=True),
        ),
    ]
