# Generated by Django 5.1.3 on 2024-11-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0004_remove_incidencia_ubicacion_incidencia_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='id_usuario_gestorTerritorial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
