# Generated by Django 5.1.3 on 2024-11-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0006_alter_incidencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='comentariosF',
        ),
    ]
