# Generated by Django 5.1.3 on 2024-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0009_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='id_usuario_departamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
