# Generated by Django 5.1.2 on 2024-10-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='nombre',
            field=models.CharField(default='Municipalidad X', max_length=255),
        ),
    ]
