# Generated by Django 5.1.2 on 2024-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_logo_delete_configuracionmunicipalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='nombre_municipalidad',
            field=models.CharField(default='Municipalidad X', max_length=255, null=True),
        ),
    ]
