# Generated by Django 5.1.2 on 2024-11-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_multimedia', models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/')),
                ('id_usuario_gestorTerritorial', models.IntegerField(blank=True, null=True)),
                ('titulo_Incidencia', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada'), ('validada', 'Validada')], default='iniciada', max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_Reporte', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('historial_Cambios_estados', models.JSONField(default=dict)),
                ('resolutor_Asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('id_usuario_departamento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.campo')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='gestor_territorial.incidencia')),
            ],
        ),
    ]
