# Generated by Django 5.1.3 on 2024-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='longitud',
            field=models.FloatField(),
        ),
    ]
