# Generated by Django 5.1.3 on 2024-11-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0003_remove_incidencia_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='historial_Cambios_estados',
        ),
    ]
