# Generated by Django 5.1.3 on 2024-11-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0004_remove_incidencia_historial_cambios_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='direccion_multimedia',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='multimedia_gestor',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/gestor'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='multimedia_resolutor',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/resolutor'),
        ),
    ]
