# Generated by Django 5.1.3 on 2024-12-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0006_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('eliminada', 'eliminada'), ('inexistente', 'inexistente'), ('iniciada', 'Iniciada'), ('verificada', 'Verificada'), ('no verificada', 'No Verificada'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('asignada', 'Asignada'), ('en proceso', 'En Proceso'), ('inconclusa', 'Inconclusa'), ('finalizada', 'Finalizada')], default='iniciada', max_length=15),
        ),
    ]
