# Generated by Django 5.1.2 on 2024-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_territorial', '0008_alter_incidencia_resolutor_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
